### ISSUE TITLE
Found 0 images belonging to 100 classes.

### ISSUE THREAD

**Issue by sarmadm** [wushidonguc/Two-stream-action-recognition-keras#4]
Hi could you please help me with this error

`(keras_v) C:\Users\Documents\deep_L_projects\two-stream-action-recognition-keras-master>python spatial_train.py

Using TensorFlow backend.
class_limit =  None
Found 0 images belonging to 100 classes.
Found 0 images belonging to 100 classes.
2018-11-05 19:11:51.685926: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX
Loading network from ImageNet weights.
Get and train the top layers...
Epoch 1/10
Traceback (most recent call last):
  File "spatial_train.py", line 109, in <module>
    main()
  File "spatial_train.py", line 106, in main
    nb_epoch=nb_epoch, name_str=name_str)
  File "spatial_train.py", line 80, in train
    model = train_model(model, 10, generators)
  File "spatial_train.py", line 19, in train_model
    callbacks=callbacks)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\legacy\interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\engine\training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\engine\training_generator.py", line 181, in fit_generator
    generator_output = next(output_generator)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\utils\data_utils.py", line 709, in get
    six.reraise(*sys.exc_info())
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\utils\data_utils.py", line 685, in get
    inputs = self.queue.get(block=True).get()
  File "C:\Users\Anaconda3\envs\keras_v\lib\multiprocessing\pool.py", line 670, in get
    raise self._value
  File "C:\Users\Anaconda3\envs\keras_v\lib\multiprocessing\pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras\utils\data_utils.py", line 626, in next_sample
    return six.next(_SHARED_SEQUENCES[uid])
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras_preprocessing\image.py", line 1526, in __next__
    return self.next(*args, **kwargs)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras_preprocessing\image.py", line 1967, in next
    index_array = next(self.index_generator)
  File "C:\Users\Anaconda3\envs\keras_v\lib\site-packages\keras_preprocessing\image.py", line 1511, in _flow_index
    current_index = (self.batch_index * self.batch_size) % self.n
ZeroDivisionError: integer division or modulo by zero`

**Comment by JoseponLee** [comment]
hi, did you slove it ,can you share the way with me ?

**Comment by mbilalshaikh** [comment]
similar issue with me , can anyone help?

Using TensorFlow backend.
class_limit =  None
Found 0 images belonging to 100 classes.
Found 0 images belonging to 100 classes.
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/tensorflow_core/python/ops/resource_variable_ops.py:1630: calling BaseResourceVariable.__init__ (from tensorflow.python.ops.resource_variable_ops) with constraint is deprecated and will be removed in a future version.
Instructions for updating:
If using Keras pass *_constraint arguments to layers.
2020-11-08 05:46:37.861750: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-11-08 05:46:37.866661: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2020-11-08 05:46:37.866705: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 99b3d1645d60
2020-11-08 05:46:37.866722: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 99b3d1645d60
2020-11-08 05:46:37.866816: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 418.67.0
2020-11-08 05:46:37.866871: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 418.67.0
2020-11-08 05:46:37.866887: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 418.67.0
2020-11-08 05:46:37.872441: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2200000000 Hz
2020-11-08 05:46:37.872733: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x28b4f40 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-08 05:46:37.872765: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/keras/backend/tensorflow_backend.py:4070: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/keras/backend/tensorflow_backend.py:4074: The name tf.nn.avg_pool is deprecated. Please use tf.nn.avg_pool2d instead.

Loading network from ImageNet weights.
Get and train the top layers...
WARNING:tensorflow:From /tensorflow-1.15.2/python3.6/keras/backend/tensorflow_backend.py:422: The name tf.global_variables is deprecated. Please use tf.compat.v1.global_variables instead.

Epoch 1/10
